### ISSUE TITLE
[Question] What on earth is hackfile.txt

### ISSUE THREAD

**Issue by skycatminepokie** [JumperOnJava/JumpersPizzeria#12]
It's made [here](https://github.com/JumperOnJava/JumpersPizzeria/blob/70f46e4a70ef63ffa5690521de530bb35d747e95/src/main/java/io/github/JumperOnJava/jjpizza/pizzamenu/slices/runnable/actionproviders/SubPizzaScreenActionProvider.java#L83). Is it just used to make sure the parent directories are made?

**Comment by JumperOnJava** [comment]
I don't know either bro 💀.
My guess from context that is probably it is to create folders for subpizzas, so I don't have to check each time if subpizza folder exist and create it manually before scanning it. It was just easier to create file there so directories are generated automatically
