### ISSUE TITLE
[Feature Suggestion] Add an option to show the menu on hold and activate selected action on release

### ISSUE THREAD

**Issue by UserSv4** [JumperOnJava/JumpersPizzeria#2]
I think it would be really nice to have an option to display the menu when the player starts holding the selected key and when the key is released activate the selected action. This way actions could be activated without even having to click any mouse buttons.

**Comment by JumperOnJava** [comment]
Sounds interesting, i will try to implement this

**Comment by JumperOnJava** [comment]
added into 1.20 branch

**Comment by JumperOnJava** [comment]
bruh i implemented it wrong (you need to press second time to activate)

**Comment by JumperOnJava** [comment]
ok now it works fine
