### ISSUE TITLE
Help / Documentation in regards to naming conventions (.png)

### ISSUE THREAD

**Issue by jbrown1597** [JumperOnJava/JumpersPizzeria#3]
I adore this mod. Thank you thank you thank you <3

However, I am having a little difficulty with the naming conventions of pngs. (EX: "minecraft:textures/block/ender_chest.png")

I can look up the minecraft ID's on google (and I'm getting by moderately successfully doing so), BUT not all work / it's difficult because none of these sites specify: "hey, this is a block / item / entity, etc."

And some of them I just CAN NOT figure out, like chests, barrels, mob heads, etc.

Any suggestions would be greatly appreciated!

P.S -
(If I recall correctly), a very similar mod I previously used - Minemenu, had similar implementation but I recall never having issues  settings pictures, as I could just type for example: Minecraft:Ender_Chest 

I'm sure it's not easy to implement, and I am unsure of how he did so - but, just wanted to throw that out there as well.

**Comment by JumperOnJava** [comment]
I know it is not pretty intuitive thing for average user, but it uses resource location. Basically that's path of texture in texturepack (including vanilla one) so for items you need to use "minecraft:textures/(item/block)/texture.png" for some items. But some items/blocks use different texture names (like furnace_top _side etc) so it is harder to find their textures. I have some ideas to improve this system but i haven't got to implementing it

**Comment by jbrown1597** [comment]
No worries & no rush. 

I'm definitely going to keep using this mod, but let me ask you this instead: 

Where are the resource locations / .png texture files stored? 
I want to be able to look up filenames so I can finish setting this bad boy up!

**Comment by JumperOnJava** [comment]
You can find textures you need in resource packs or in minecraft jar files (assets/minecraft)
Also you can add your own icons in resourcepacks:
create resourcepack, in assets folder create folder with lowercase name and any texture in in should be accesible by foldername:texture.png

**Comment by jbrown1597** [comment]
Just wanted to say thanks again! I got everything setup & DAMN it's looking nice <3

https://imgur.com/a/o3dqVaU

One last thing!
Feature request: Ability to delete segments. If you make one too many, you gotta start over! lol

**Comment by JumperOnJava** [comment]
What do you mean by deleting segments? You can already do this by clicking red part of segment in middle (in edit mode)

**Comment by JumperOnJava** [comment]
Hey @jbrown1597. In recent update (for 1.20.2) i added now icon selection menu! Now it is user friendly...  
https://media.discordapp.net/attachments/507982666755473427/1155482616825380945/2023-09-24_14.20.51.png?width=1193&height=671
