### ISSUE TITLE
Feature Request - Sub Menu

### ISSUE THREAD

**Issue by DahliaSR** [JumperOnJava/JumpersPizzeria#4]
Great idea, will try it now.
But I am already missing one feature.
The ability to have submenus associated with a slice.
Say I open the menu and see a configured slice called `Homes`, I click on it and a sub-menu (sub-pizza) opens showing all my configured homes.
That would be a great feature.

**Comment by JumperOnJava** [comment]
Yeah i like this idea. I will try to implement when i will have some free time.

**Comment by JumperOnJava** [comment]
Addded. I will post it on modrinth as soon as i can, but now you can download it from [here (you need to downloadArtifact)](https://github.com/JumperOnJava/JumpersPizzeria/actions/runs/6298976872)

**Comment by DahliaSR** [comment]
Awesome, I will give it a try, as soon as I can upgrade my MC version to 1.20.2

**Comment by DahliaSR** [comment]
Okay, just wanted to try it. But it requires 1.20.2 RC 2 - useless like this. I`ll wait till a version for 1.20.2 is available.

**Comment by JumperOnJava** [comment]
Oh. Looks like i forgot to add 1.20.2 into fabric.mod.json

**Comment by DahliaSR** [comment]
> Oh. Looks like i forgot to add 1.20.2 into fabric.mod.json

if that is all, I can overwrite it myself in the json file. will suffice for testing

**Comment by JumperOnJava** [comment]
I just updated it in repository

**Comment by JumperOnJava** [comment]
posted to modrinth

**Comment by DahliaSR** [comment]
> posted to modrinth

yeah, I've just seen that.
also a version fpr 1.20.1.
Just gave it a try and for now it does what I want. NOt very user friendly yet, but the key features nee d to have priority.
I'll play around with it. I'm sure I can make some more suggestions regarding the fine tuning of the current features and some more features as well.
Nice job so far
